---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/exciteconstruct/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp site.webmanifest $DEPLOYPATH
    - /bin/cp *.png $DEPLOYPATH
    - /bin/cp *.jpg $DEPLOYPATH
    - /bin/cp *.jfif $DEPLOYPATH
    - /bin/cp *.pdf $DEPLOYPATH